# Generated by Django 4.0.3 on 2022-03-17 12:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cont',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
