# Generated by Django 4.0.3 on 2022-03-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='note_id',
            new_name='note',
        ),
    ]
