# Generated by Django 4.0.3 on 2022-03-17 17:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_cont_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cont',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cont_up',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
