# Generated by Django 4.0.3 on 2022-03-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_note_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='post',
            new_name='note',
        ),
    ]
