# Generated by Django 4.0.3 on 2022-03-19 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='note',
        ),
        migrations.AddField(
            model_name='response',
            name='notenote',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.note', verbose_name='id_объявления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id_пользователь'),
        ),
    ]
