# Generated by Django 4.0.3 on 2022-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_response_note_alter_response_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='user_response',
            field=models.ManyToManyField(to='main.response'),
        ),
    ]
